name: Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-variable: [1, 3]
    steps:
      name: test
      run: echo ${{ matrix.test-variable}}
